# Generated by Django 3.1.7 on 2021-04-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_profile', '0002_auto_20210404_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='time/avatars/'),
        ),
    ]
