# Generated by Django 3.2.4 on 2021-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
