# Generated by Django 3.1.7 on 2021-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_task', '0003_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
