# Generated by Django 3.2.4 on 2021-06-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210606_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='class_belong',
            new_name='course_name',
        ),
    ]
