# Generated by Django 3.2.4 on 2021-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0003_rename_class_belong_courseinfo_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classduration',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
    ]
