# Generated by Django 3.2.4 on 2021-06-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_signals_app', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total', models.PositiveIntegerField(blank=True)),
                ('total_price', models.PositiveIntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_signals_app.car')),
            ],
        ),
    ]
