# Generated by Django 3.2.4 on 2021-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_signals_app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cars',
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(to='dj_signals_app.Car'),
        ),
    ]
