# Generated by Django 3.1.7 on 2021-03-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_vendor', '0001_initial'),
        ('eco_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='eco_vendor.vendor'),
        ),
    ]
